### ISSUE TITLE
Implement android app display on webpage

### ISSUE THREAD

**Issue by anandwana001** [anandwana001/anandwana001.github.io#4]
I would like to implement something like this in this repository. 
Reference:- https://cswithandroid.withgoogle.com/
@vivekghanchi @Harshvardhan58 if you could help on this issue!

![image](https://user-images.githubusercontent.com/25057618/32590201-21d54170-c53f-11e7-827a-fb456ac93d2d.png)

**Comment by Harshvardhan58** [comment]
Do you mean that you want to implement the phone simulation as shown in the reference?@anandwana001

**Comment by anandwana001** [comment]
@Harshvardhan58 Yes
